### ISSUE TITLE
Consider automating builds using Travis (or other) CI

### ISSUE THREAD

**Issue by tomreyn** [AquariaOSE/Aquaria#11]
**Continuous integration** allows you to quickly tell whether or not your latest commits are building fine. You could also use it to build test builds for those willing to test but unable / unwilling to build themselves.

**Travis CI** is a free-for-free-software hosted platform which combines a central CI system with free (Ubuntu 12.04 LTS running in OpenVZ containers) build nodes, supporting several versions of gcc and clang, which integrates well with GitHub. (There are alternatives to Travis, some of which also provide free Windows builds - let me know if interested or just check the comparison on Wikpedia)

Getting started with Travis CI is easy. Here's an example `.travis.yml` file which is used to build MegaGlest using both gcc/cpp and clang/clang++:
https://github.com/MegaGlest/megaglest-source/blob/develop/.travis.yml
(You will find many more on GitHub.)

Your `.travis.yml` file needs to be placed in the main repository directory of the branches you wish to build. Then you can login at https://travis-ci.org/ (you can and must use your existing GitHub account via OpenID to do so), select what you want built, and that's it. On your next commit to any watched branch, your code will be automatically built and you will receive notifications as configured.

Here's an example Aquaria `.travis.yml` (and a Linux build script in case you prefer to place the build commands in the repository as a whole and just call this script when building - makes it easier to modify plus you get free versioning):
https://gist.github.com/tomreyn/2ed4ed1c4937a6f56bb0

**Comment by Cat-Ion** [comment]
We can close this one :p
