### ISSUE TITLE
Recipe list: Vedha sea crisp: Excess blank space

### ISSUE THREAD

**Issue by tomreyn** [AquariaOSE/Aquaria#15]
There appears to be an extra blank space in the "Any B_one" ingredient to Vedha sea crisp on the recipes list:

![aquaria_recipes_typo_excess_blank_space](https://cloud.githubusercontent.com/assets/1328851/5592352/62d21b94-91cb-11e4-9cb9-22814f1e2f6b.png)

Indeed thats a super mini bug, but it still seems wrong and - I assume - will be easy to fix. I was looking at the text files in files/data but could not immediately spot what would be wrong there.

**Comment by fgenesis** [comment]
Fixed in experimental \o/
