### ISSUE TITLE
Random segfaults when using energy form

### ISSUE THREAD

**Issue by DarwinAwardWinner** [AquariaOSE/Aquaria#24]
I'm trying to play Aquaria on OSX using this open-source code from this repo. However, I'm running into repeated crashes, always while shooting projectiles using the energy form. I got through the entire intro up to the energy temple with no crashes, and then once I got the energy form, I started getting random crashes, anywhere from the very first energy shot I take after loading my game, to 20 minutes in. I've attached 3 backtraces provided by OSX when programs crash. All 3 seem to have different stack traces, so I'm not sure how useful they would be in debugging. Let me know if you want me to generate more backtraces or need any other info. I compiled the binary from commit 6971e7898fd0d9f36876da502b055426d31e34df.

[crash1.txt](https://github.com/AquariaOSE/Aquaria/files/143781/crash1.txt)
[crash2.txt](https://github.com/AquariaOSE/Aquaria/files/143782/crash2.txt)
[crash3.txt](https://github.com/AquariaOSE/Aquaria/files/143780/crash3.txt)

**Comment by MaddTheSane** [comment]
It looks like you’re building it against SDL 1.2. Have you tried compiling it against SDL2?

**Comment by DarwinAwardWinner** [comment]
Would I do that by adding `-DAQUARIA_USE_SDL2=1` to the cmake invocation?

**Comment by DarwinAwardWinner** [comment]
After compiling with the above option, I now still get random segfaults when using the energy form, but the stack trace looks different (I think). See attached files:

[sdl2-crash1.txt](https://github.com/AquariaOSE/Aquaria/files/143891/sdl2-crash1.txt)
[sdl2-crash2.txt](https://github.com/AquariaOSE/Aquaria/files/143892/sdl2-crash2.txt)

**Comment by MaddTheSane** [comment]
Yeah, those are different: Now it’s crashing in a specific place (OggDecoder thread).

**Comment by fgenesis** [comment]
Do you link against the shitty OSX system OpenAL or do you use a proper implementation like http://kcat.strangesoft.net/openal.html? I always link against that (on win, linux, osx) and haven't heard of any problems related to that.

**Comment by DarwinAwardWinner** [comment]
Well, I *think* I compiled with the Homebrew-provided Strangesoft OpenAL, which gives these directions:

> If you build your own software and it requires this formula, you'll
> need to add to your build variables:
> 
>     LDFLAGS:  -L/usr/local/opt/openal-soft/lib
>     CPPFLAGS: -I/usr/local/opt/openal-soft/include

I read somewhere that cmake doesn't respect CPPFLAGS, so I also included them in CFLAGS and CXXFLAGS:

```
$ env | grep FLAGS
LDFLAGS=-L/usr/local/opt/openal-soft/lib
CPPFLAGS=-I/usr/local/opt/openal-soft/include
CXXFLAGS=-I/usr/local/opt/openal-soft/include
CFLAGS=-I/usr/local/opt/openal-soft/include
```

When doing `make VERBOSE=1`, I see lines like this:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DAQUARIA_BUILD_CONSOLE=1 -DAQUARIA_B
UILD_SCENEEDITOR=1 -DAQUARIA_INTERNAL_FTGL=1 -DBBGE_BUILD_ACHIEVEMENTS_INTERNAL=1 -DBBGE_BUILD_FMOD_OPENAL_BRIDGE=1 -DBBGE_BUILD_F
RAMEBUFFER=1 -DBBGE_BUILD_MACOSX=1 -DBBGE_BUILD_OPENGL=1 -DBBGE_BUILD_OPENGL_DYNAMIC=1 -DBBGE_BUILD_SDL2=1 -DBBGE_BUILD_SDL=1 -DBB
GE_BUILD_SHADERS=1 -DBBGE_BUILD_UNIX=1 -DBBGE_BUILD_VFS=1 -DBBGE_SKIP_CONFIG_HEADERS=1 -DBBGE_USE_GLM=1 -DGL_GLEXT_LEGACY=1 -DHAVE
_PUTENV=1 -DHAVE_STRCASECMP -DLUA_USE_ULONGJMP=1 -DNDEBUG -DTIXML_USE_STL=1 -DVFS_ENABLE_C_API=1 -I/Users/ryan/src/Aquaria/BBGE -I
/Users/ryan/src/Aquaria/BBGE/GL -I/Users/ryan/src/Aquaria/ExternalLibs/glpng/zlib -I/Users/ryan/src/Aquaria/ExternalLibs/glpng/png
 -I/Users/ryan/src/Aquaria/Aquaria -I/Users/ryan/src/Aquaria/ExternalLibs/FTGL/include -I/Users/ryan/src/Aquaria/ExternalLibs/free
type2/include -I/Users/ryan/src/Aquaria/ExternalLibs/lua-5.1.4/src -I/Users/ryan/src/Aquaria/ExternalLibs/libogg-1.3.0/include -I/
Users/ryan/src/Aquaria/ExternalLibs/libvorbis-1.3.3/include -I/Library/Frameworks/SDL2.framework/Headers -I/System/Library/Framewo
rks/OpenAL.framework/Headers -I/Users/ryan/src/Aquaria/ExternalLibs -I/Users/ryan/src/Aquaria/ExternalLibs/ttvfs -I/Users/ryan/src
/Aquaria/ExternalLibs/ttvfs_zip -I/Users/ryan/src/Aquaria/ExternalLibs/ttvfs_cfileapi  -I/usr/local/opt/openal-soft/include  -O3 -
DNDEBUG   -o CMakeFiles/aquaria.dir/Aquaria/Demo.cpp.o -c /Users/ryan/src/Aquaria/Aquaria/Demo.cpp
```

And I see that `-I/System/Library/Frameworks/OpenAL.framework/Headers` appears before `-I/usr/local/opt/openal-soft/include`. I have no idea which one takes precedence. Is there any way to check which one it got compiled/linked against? In any case, it compiled successfully and gave a similar backtrace:

[sdl2-crash3.txt](https://github.com/AquariaOSE/Aquaria/files/145025/sdl2-crash3.txt)

**Comment by fgenesis** [comment]
> Is there any way to check which one it got compiled/linked against?

```otool -L```

Also, to exclude more crash possibilities, please use -O2 instead of -O3. I have a version of mingw32 that used to miscompile Aquaria with -O3  to crash when most maps were loaded.

Instead of polluting the shell env, why don't you just use ccmake or cmake-gui and adjust the flags there? Much simpler.

Anyway, I guess i should just pull openalsoft into ExternalLibs and build the local version by default. Same as with the other external libs residing in the repo.

I'll check if i can pinpoint the issue but so far everything looks good here...

**Comment by DarwinAwardWinner** [comment]
Ok, after using ccmake to set the compiler options properly and using otool to verify that it was indeed built against the correct OpenAL, I was able to play for 30 minutes, spamming the energy shot as much as possible, without any crashes. I'll keep testing it, but early indications are good.

**Comment by DarwinAwardWinner** [comment]
Just played for another hour of heavy energy form combat with still no crashes. I think we can call this resolved. Solution: don't compile against Apple's OpenAL.

**Comment by fgenesis** [comment]
Alright, thanks! If it turns out there are still problems please reopen.
I'll see if i can put openALsoft into the repo and make that the default, to avoid this happening for others.
