### ISSUE TITLE
clicking is ignored (GOG's aquaria)

### ISSUE THREAD

**Issue by AloisMahdal** [AquariaOSE/Aquaria#40]
I just built Aquaria using instructions in README (I also had to `sudo apt-get install libsdl1.2-dev libopenal-dev`) and I'm running it with this script:

```
#!/bin/sh
export AQUARIA_DATA_PATH="$HOME/local/GOG Games/Aquaria/game"
exec "$HOME/vcs.upstream/Aquaria/cmake-build/aquaria"
```

Game seems to start fine, but all mouse clicks are ignored. I can move the mouse around and cursor does change when hovering above a button, but nothing happens when I click. All I can do is to hit `Ctrl-Alt-F3` to switch outside X, log in and `killall aquaria`.

I tried to run from terminal as well but no interesting output is logged (just the hint about rumble). Also tried to change resolution and run in windowed mode; no avail.

This is Debian Jessie with Aquaria from GOG (v2.0.0.4 / 1.1.3).

Please let me know what info should I provide.

**Comment by fgenesis** [comment]
The README file in the repo explains what you have to do. The issues you have typically mean you didn't update your scripts (in one of the 3 ways described there). Just make sure the game loads the scripts from the repo (and also the other updated data files) instead of the originals and you should be fine.

**Comment by AloisMahdal** [comment]
You're right, my bad. I misunderstood the README -- I was following the second option (update frequently) I thought everything above "Alternatively" should be enough and below that is the "other alternative".

I followed the rest and now it works like a charm.

Thanks!
