### ISSUE TITLE
Header confusion

### ISSUE THREAD

**Issue by chewi** [AquariaOSE/Aquaria#55]
I've noticed that the bundled tinyxml2.h is still used even if you ask to use the system copy. This is because ExternalLibs is always in the include path. This header would need to be moved into a subdirectory.

I can't see any other instances where this would happen unless I unbundle GLPNG. The glpng.h header is normally placed in /usr/include/GL so the sources would be changed to `#include <GL/glpng.h>`. Putting the bundled header in ExternalLibs/GL would then hit the same problem so perhaps it should be ExternalLibs/glpng/GL.

There are other headers in ExternalLibs/GL but I'm not sure why. They are almost identical to the ones in BBGE/GL. Are they there for the partially bundled SDL? If not, I think they should go.

And before you moan about my unbundling, you'll be glad to know I'm not bothering to package BBGE and ttvfs separately now. :wink:

**Comment by fgenesis** [comment]
Yeah, it can go into ExternalLibs/tinyxml2/timyxml2.*, no? And glpng.h should go to the right subdir as well.
Ok, easy, will do this later today when back from work.

> the glpng.h header is normally placed in /usr/include/GL

o_O

> Are they there for the partially bundled SDL? If not, I think they should go.

No, i think they were leftovers from an earlier restructuring. Need to check what is actually used and what isn't.

> you'll be glad to know I'm not bothering to package BBGE and ttvfs separately now. 😉

<3

(That said, i've become to realize what a turd ttvfs is. The urge to rewrite is strong, but i don't have time...)

**Comment by chewi** [comment]
> o_O

Yeah, I found that a bit odd too but if you check the glpng package from the various Linux distributions, they've all put it there.

I can do the work, just wanted to check what you thought about it first.

**Comment by fgenesis** [comment]
Ok great, go ahead.
