### ISSUE TITLE
-DAQUARIA_INTERNAL_TINYXML2=off build fails when tinyxml2 >= 5.0.0

### ISSUE THREAD

**Issue by jbeich** [AquariaOSE/Aquaria#59]
Regressed by leethomason/tinyxml2@584af570860b, see also leethomason/tinyxml2#498.

```
Aquaria/Continuity.cpp:(.text+0x1684e): undefined reference to `tinyxml2::StrPair::GetStr()'
CMakeFiles/aquaria.dir/Aquaria/DSQ.cpp.o: In function `DSQ::loadModsCallback(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, long)':
Aquaria/DSQ.cpp:(.text+0x1014e): undefined reference to `tinyxml2::StrPair::GetStr()'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

http://beefy9.nyi.freebsd.org/data/110amd64-default/444089/logs/aquaria-1.002.22_1.log

**Comment by fgenesis** [comment]
Hm, this is an upstream bug, no? Why don't you use the internal tinyxml2 in that case?

(Same for glm, i have a quite old version in there on purpose -- one that still works in msvc2008!)

**Comment by jbeich** [comment]
Builds fine against TinyXML2 5.0.1, see leethomason/tinyxml2@8c9e3133c4cc.
