### ISSUE TITLE
Error at 33% when attempting make on RPi4

### ISSUE THREAD

**Issue by pelupessy** [AquariaOSE/Aquaria#61]
I have been attempting a build on the new Raspberry Pi 4 (Retropie). Following the instructions, I get the following error at 33%:

```
..Aquaria/BBGE/Base.cpp:1191:8:SIGTRAP was not declared in this scope raise(SIGTRAP)
```
and building halts. 

EDIT: Adding signal.h to the includes of that file fixes it.

**Comment by fgenesis** [comment]
Done, thanks for pointing this out. But you could have used <signal.h>, as it should be ;)
