### ISSUE TITLE
Non-existing textures are sometimes displayed (e.g. capes on constumes which don't have one)

### ISSUE THREAD

**Issue by dimag0g** [AquariaOSE/Aquaria#72]
Steps to reproduce:

- Obtain a costume without a cape (e.g. seahorse) and wear it
- Save the game and quit
- Load the game again, an empty sprite appears as a cape:

![2020123021150600-FD9C2C2EDC9ABCBFF4553C95203A203B](https://user-images.githubusercontent.com/10945319/103379200-242fa300-4ae5-11eb-8675-03b21d9e8b27.jpg)

Root causes:
- Costumes without a cape rely on a failure to load a non-existent sprite, `gfx/naija/cape-costume_name.png`. In general, relying of a failure handling mechanism for normal execution is buggy.
- `RenderObject::setTexture` creates a texture even if the file is not found. This avoids crashes on missing textures, but on the other hand errors with missing textures are masked until the missing texture is clearly visible by the user.

A possible stop-gap fix is https://github.com/dimag0g/Aquaria/commit/4238741f3927fc69984bf5aa064dec9f2a145215

**Comment by fgenesis** [comment]
I think I had fixed it in https://github.com/AquariaOSE/Aquaria/commit/8bd40be8aa624be03eac07213ef0fe2fa6578dc5 but that hasn't made it into master yet (why? I have no idea. Should merge i guess).

**Comment by dimag0g** [comment]
Yep, I switched to experimental branch and the issue is gone.
