### ISSUE TITLE
Error!: Variables data not found! Aborting...

### ISSUE THREAD

**Issue by karriszou** [AquariaOSE/Aquaria#77]
I build game on Ubuntu 20.04, and when i run it, the following error occurred: "Error!: Variables data not found! Aborting...". It seems that the 'data/variables.txt' file is missing, where can i find it?

**Comment by fgenesis** [comment]
You need the game data files. Buy the game. (This repo has only the code; the other game data are still commercial)
Once you have those, make sure the binary is run from the correct location or has the correct working directory set so it finds its files in the correct location.
